[Fixes #182]Change error message
Auto-DL/Auto-DL pull request #191
Opened 2021-06-25 14:04 UTC by TraXIcoN

## Pull Request

fixes #182  

### Description
Hardcoded error messages

### Checklist:
- [x] Followed the guidelines mentioned in our [Contributing document](/CONTRIBUTING.md)
- [x] Ensured that there aren't other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change
- [x] This PR is linked to an [Issue](https://www.github.com/Auto-DL/Generator/issues) and the issue number has been mentioned in the title and body of the PR
- [x] The code is clean and docstrings have been added or updated as required
- [x] Code is linted/formatted locally prior to submission (using `black`)

2021-06-25 20:34 UTC, shintan777 requested changes
Please remove the comment lines saying what you did

2021-06-25 21:02 UTC, TraXIcoN commented
> Please remove the comment lines saying what you did

 Really sorry I missed them again!
 Made the changes required

2021-06-26 10:09 UTC, shintan777 approved these changes

2021-06-29 19:18 UTC, ADI10HERO approved these changes

2021-06-29 19:18 UTC, merged