[Fixes #157] Flask app for model deployment
Auto-DL/Auto-DL pull request #233
Opened 2021-07-05 12:41 UTC by Onkar302

## Pull Request

fixes #157 

### Description
* Added Flask app for model deployment with folder name flaskv1 inside v1 folder.

### Checklist:
- [x] Followed the guidelines mentioned in our [Contributing document](../CONTRIBUTING.md)
- [x] Ensured that there aren't other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change
- [x] This PR is linked to an [Issue](https://www.github.com/Auto-DL/Generator/issues) and the issue number has been mentioned in the title and body of the PR
- [x] The code is clean and docstrings have been added or updated as required
- [x] Code is linted/formatted locally prior to submission (using `black`)

Signed-off-by: Onkar302 onkarbhatlawande@gmail.com

2021-07-07 13:06 UTC, ADI10HERO requested changes
Please make the discussed changes.

2021-07-10 13:15 UTC, Onkar302 commented
> Please make the discussed changes.

Implemented the changes kindly have a look.

2021-07-12 15:38 UTC, shintan777 requested changes

2021-07-12 15:38 UTC, shintan777 commented on BackEndApp/v1/flaskv1/templates/index.html
> +</html>
```suggestion
</html>

```

2021-07-12 15:38 UTC, shintan777 commented on BackEndApp/v1/flaskv1/templates/result.html
> +</html>
```suggestion
</html>

```

2021-07-13 08:58 UTC, Onkar302 commented
Does that mean adding an empty line at the end of both the HTML files?

2021-07-13 14:21 UTC, Onkar302 commented
Done, please have a look.

2021-07-15 09:46 UTC, closed without merging