[Fixes #263] Tests CRUD of the Application - Read Projects
Auto-DL/Auto-DL pull request #264
Opened 2021-07-28 08:20 UTC by McTechie

# Pull Request

## What does this PR do?
Fixes #263

The following are the ways in which the tests have been catered to:
- Isolated testing to the Frontend (tests do not verify the correctness of the Backend APIs).
- Prevented mocking axios requests in order to test like an actual user, as well as reduce requests cost to the server.
- Configured **Mock Service Worker** (MSW) to intervene axios requests.
- Created mocks and handlers for "Read Projects" part of the CRUD of the app.

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

2021-07-31 12:08 UTC, ADI10HERO requested changes

2021-07-31 12:08 UTC, ADI10HERO commented on FrontEndApp/v1-react/src/mocks/resolvers/readProjectsResolver.js
> +}
```suggestion
}

```

2021-07-31 12:08 UTC, ADI10HERO commented on FrontEndApp/v1-react/src/mocks/resolvers/createProjectsResolver.js
> +}
```suggestion
}

```

2021-07-31 14:33 UTC, McTechie commented on FrontEndApp/v1-react/src/mocks/handlers.js
> +export { handlers, rest };
Yes... I'll do the same xD

2021-07-31 14:34 UTC, McTechie commented on FrontEndApp/v1-react/src/Components/MainApp/__test__/Homeindex.test.js
> +// });
Ahh it was for the next CRUD operation... but i've removed the code (will add it from scratch for the next pull request)

2021-07-31 14:36 UTC, McTechie commented
@ADI10HERO @rajraj889 I've made the suggested changes... and will be creating new PRs on the other CRUD operations as well

2021-07-31 23:42 UTC, ADI10HERO approved these changes
@McTechie  The tests are passing but can you have a look into why this is happening when I run tests?

![image](https://user-images.githubusercontent.com/39651310/127754788-21c4eb77-a310-4619-bd62-2bd2e76f9fd1.png)

I will create an issue for this if you feel its an issue

2021-08-01 05:17 UTC, McTechie commented
@ADI10HERO thanks for pointing this out... I have verified that two of these console errors were appearing because of a few bugs in our frontend (ProjectTable.js) code... I have rectified these and now the tests should pass without any console errors.
However, there are a few more errors and warnings onto the console of the frontend.... so I'll try to create an issue regarding fixing the same.

2021-08-01 11:22 UTC, ADI10HERO commented
I am still getting the `console.error` when running all tests please create the issue.

2021-08-01 11:22 UTC, merged