Test Create and Edit Project modal render
Auto-DL/Auto-DL pull request #281
Opened 2021-08-02 06:20 UTC by McTechie

# Pull Request

## What does this PR do?
Fixes #280 

- Refactored the UI (project modals - create / edit & clone) and logic (create / edit & clone operations) to facilitate simplified testing.
- Implemented tests to verify the correct rendering of the Create and Edit Project modals (and functionality of the forms within).

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

2021-08-11 14:09 UTC, rajraj889 requested changes
Share/clone functionality successfully happens but shows error msg. Also let me know if this is getting replicated in your machine.

2021-08-11 17:03 UTC, McTechie commented
> Share/clone functionality successfully happens but shows error msg. Also let me know if this is getting replicated in your machine.

@rajraj889 The Clone functionality seems to work correctly on my machine. Also, for the Share functionality... it appears that System Admin privileges are required......? 

![image](https://user-images.githubusercontent.com/69250084/129071795-0011376b-d36f-4b8e-890b-2cef893ce98b.png)

2021-08-15 21:08 UTC, ADI10HERO approved these changes

2021-08-15 21:09 UTC, ADI10HERO commented
I approved as the bug mentioned is fixed by @shintan777

2021-08-15 21:09 UTC, merged