[Fixes #273] Workflow for pytest
Auto-DL/Auto-DL pull request #286
Opened 2021-08-05 13:31 UTC by bamblebam

# Pull Request

## What does this PR do?
Fixes #273 

Add github workflow to check python tests via pytest.

## What part does this affect?
- [ ] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [x] Other. (Please specify below)
CI/CD

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [ ] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [ ] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

2021-08-06 11:09 UTC, RusherRG commented
@bamblebam there is one check failing just try to fix it in the PR. Also, try to figure out why it hasn't been detected so far. Probably, might be because of a new update to CodeQL

2021-08-06 17:51 UTC, RusherRG requested changes
@bamblebam there is one check failing just try to fix it in the PR. Also, try to figure out why it hasn't been detected so far. Probably, might be because of a new update to CodeQL

2021-08-07 05:57 UTC, bamblebam commented
@RusherRG I fixed it by commenting the line that was causing the issue. If it doesn't break anything we can remove it later.

2021-08-07 08:48 UTC, RusherRG approved these changes

2021-08-07 08:50 UTC, RusherRG requested changes
Just have a look at frontend-CI workflow and accordingly change the on event trigger and the name of the workflow to Backend CI

2021-08-08 10:34 UTC, RusherRG approved these changes

2021-08-09 12:11 UTC, ADI10HERO requested changes
Can we add caching please?

2021-08-09 12:15 UTC, bamblebam commented
@ADI10HERO what do we want to cache ?

2021-08-09 12:23 UTC, ADI10HERO commented
@bamblebam 
Hey, good question...

Python dependencies so the subsequent builds are faster till the cache is valid.
[Reference](https://github.com/actions/cache/blob/main/examples.md#python---pip)

2021-08-09 12:44 UTC, bamblebam commented
alright

2021-08-10 07:33 UTC, ADI10HERO requested changes
I hope the changes are self-explanatory!
If not please feel free to start a convo on slack :)

2021-08-10 07:33 UTC, ADI10HERO commented on .github/workflows/backend-ci.yml
> +        python-version: [3.8]
```suggestion
        python-version: [3.8]
    defaults:
      run:
        working-directory: ./BackEndApp
```

2021-08-10 07:33 UTC, ADI10HERO commented on .github/workflows/backend-ci.yml
> +          cd BackEndApp
```suggestion
```

2021-08-10 08:42 UTC, ADI10HERO approved these changes

2021-08-10 08:42 UTC, merged