[Fixes #310] Recommendation system for model layers
Auto-DL/Auto-DL pull request #313
Opened 2021-09-01 15:57 UTC by VedantMahadik

Signed-off-by: VedantMahadik <therookie636@gmail.com>

# Pull Request

## What does this PR do?
Fixes #310
Shows top two recommendations for model layers, which gives users suggestions depending on the latest three layers added.

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [ ] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

2021-09-02 07:23 UTC, bamblebam approved these changes

2021-09-02 16:31 UTC, ADI10HERO requested changes

2021-09-02 16:31 UTC, ADI10HERO commented on FrontEndApp/v1-react/src/Components/MainApp/Step2.js
> +			.post("http://localhost:8080/predict", {
```suggestion
			.post("http://localhost:8080/predict", {
```

Please use env variables.

2021-09-08 13:17 UTC, ADI10HERO commented
Add the following to frontend `.env` file: `REACT_APP_FASTAPI_URL`

2021-09-08 13:19 UTC, ADI10HERO commented
@rajraj889 
The code looks okay but is it placed correctly? Or should the API call be in a service file and just a call to that function from here?

2021-09-08 13:22 UTC, rajraj889 commented
@ADI10HERO Yes it's a practice we are following, so it would be great if it's in service file.

2021-09-13 21:13 UTC, ADI10HERO commented
@VedantMahadik  I tried resolving conflicts using the Github UI, but the 3rd Step2 conflict confused me, leaving this to you :P

2021-09-17 10:26 UTC, ADI10HERO commented
@bamblebam  Reminder :)

2021-09-17 10:46 UTC, bamblebam commented
Yeah I will solve them this week

2021-09-19 17:02 UTC, VedantMahadik commented
Sorry for the delay, I have merged the branches please review it.

2021-09-20 07:04 UTC, ADI10HERO approved these changes

2021-09-20 07:05 UTC, merged