Run.sh new frontend support #452
Auto-DL/Auto-DL pull request #480
Opened 2022-01-23 18:52 UTC by ashish-ad

# Pull Request

## What does this PR do?
Fixes #452

This PR is related to a feature improvement in auto-dl for giving options for the installation of two front-end versions.
The motivation behind the PR is related to WOC2.0 participation.

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [x] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

2022-01-25 05:05 UTC, McTechie requested changes
Good work! Just a few changes would be required xD

2022-01-25 05:05 UTC, McTechie commented on scripts/run.sh
> +    echo "  2) Version 2"
```suggestion

    echo "************ Select a Version for the Frontend Setup ************"
    echo "  1) Version 1 (React Client)"
    echo "  2) Version 2 (NextJS Client)"
```

2022-01-25 05:05 UTC, McTechie commented on scripts/run.sh
> +        1) frontend_setup;;
```suggestion
        1) frontend_setup_v1;;
```

2022-01-25 05:05 UTC, McTechie commented on scripts/run.sh
>      frontend_setup
```suggestion
```

2022-01-25 18:48 UTC, ashish-ad commented
Hey @McTechie, I have merged all the changes as u suggested and _I wanted to learn how do you do this, I mean the suggestion of changes but suggesting certain lines to be changed because I too want to learn this as I am too a collaborator maintainer I too want to learn this._
And I think the branch is ready to get merged in the main branch.

2022-01-26 13:12 UTC, McTechie commented
> Hey @McTechie, I have merged all the changes as u suggested and _I wanted to learn how do you do this, I mean the suggestion of changes but suggesting certain lines to be changed because I too want to learn this as I am too a collaborator maintainer I too want to learn this._ And I think the branch is ready to get merged in the main branch.

@ashish-ad, great work! The script looks good to me, although there would be another review required prior to merging this PR. 

As for suggesting changes, all you gotta do is select the '+' icon next to the line you want to suggest a change following which you would select the '+-' icon shown on a tab above the textarea. If this sounds too confusing, going through [this guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review) would be very beneficial. 😄✨

2022-01-27 07:53 UTC, ashish-ad commented
Thank you @McTechie.

2022-01-27 07:58 UTC, RusherRG approved these changes

2022-01-27 09:05 UTC, ashish-ad commented
Now is this branch ready to merge ?!

2022-02-06 16:43 UTC, ashish-ad commented
Hello @RusherRG, Will, this PR will be getting merged, or do I need to do some more changes to it.
please let me know.

2022-02-06 16:45 UTC, RusherRG commented
> Hello @RusherRG, Will, this PR will be getting merged, or do I need to do some more changes to it. please let me know.

Hey sorry for the delay. Don't worry we'll merge it, there's no need for any changes.

2022-02-08 18:31 UTC, merged