feat: Rendering the generated code before downloading the file
Auto-DL/Auto-DL pull request #483
Opened 2022-01-25 08:42 UTC by AmitGupta7580

# Pull Request

## What does this PR do?
Fixes #324

![image](https://user-images.githubusercontent.com/57043342/150941665-d0dd5faf-5b51-40e3-8e24-d3eac6feda0a.png)

## What part does this affect?
- [x] FrontEnd.
- [ ] BackEnd.
- [ ] Documentation.
- [ ] Other. (Please specify below)

## Before submitting
- [x] Was this discussed/approved via a GitHub issue or slack?
- [x] Did you read the [contributor guideline](https://github.com/Auto-DL/Auto-DL/blob/v1-beta/CONTRIBUTING.md)?
- [x] Did you ensure that there aren't any other open [Pull Requests](https://www.github.com/Auto-DL/Generator/pulls) for the same update/change?
- [x] Did you make sure the title is self-explanatory and the description concisely explains the PR?
- [x] Did you make sure your PR does only one thing, instead of bundling different changes together?
- [x] Did you make sure the code is clean and docstrings have been added or updated as required?
- [x] Did you make sure the code is linted/formatted locally prior to submission? (using `black` and/or `prettier`)
- [x] Did you make sure to update the documentation with your changes? (if necessary)

## PR review
Anyone in the community is free to review the PR once the tests have passed.

Thank you for contributing to [AutoDL](https://github.com/Auto-DL/Auto-DL). We look forward to your continued support.

2022-01-27 14:26 UTC, ADI10HERO reviewed
LGTM

2022-01-27 14:26 UTC, ADI10HERO commented
@McTechie  could you please review as well? :)

2022-01-28 05:53 UTC, McTechie requested changes
The functionality looks good to me, just a few UI changes xD

2022-01-28 05:53 UTC, McTechie commented on FrontEndApp/v1-react/src/Components/MainApp/Step2.js
>          <DialogTitle onClose={handleCloseModal}>Code Generated!</DialogTitle>
```suggestion
        <DialogTitle onClose={handleCloseModal}>Great Work!</DialogTitle>
```

2022-01-28 05:53 UTC, McTechie commented on FrontEndApp/v1-react/src/Components/MainApp/Step2.js
> +          <p style={{whiteSpace: 'pre'}}> { code } </p>
```suggestion
          <div>
            <h3>Generated Code:</h3>
            <p style={{ whiteSpace: 'pre' }}>
              { code }
            </p>
            
            <hr />

            <h3>Instructions:</h3>
            <ul>
              <li>
                Click the "Download Code" button to download the generated code
                to any directory of your choice.
              </li>
              <br></br>
              <Tooltip title="See value of 'base' variable in the python file">
                <li>
                  Make sure you place the data files relative to the downloaded
                  script
                </li>
              </Tooltip>
              <br></br>
              <li>
                <Tooltip
                  title="Exmaple: python3 test.py"
                  placement="bottom-start"
                >
                  <div> Run the code.</div>
                </Tooltip>
              </li>
            </ul>
          </div>
```

2022-02-02 19:51 UTC, AmitGupta7580 commented
@ADI10HERO @McTechie I have updated the UI as requested have a look on the changes.

2022-02-03 06:35 UTC, McTechie approved these changes
Looks good to me xD

2022-02-03 07:13 UTC, merged